# Generated by Django 6.0.5 on 2026-05-17 13:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('step_type', models.CharField(choices=[('text', 'Текст'), ('video', 'Видео'), ('quiz', 'Тест'), ('test_case', 'Тест-кейс'), ('sort', 'Сортировка'), ('match', 'Сопоставление')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('points', models.PositiveIntegerField(default=1)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='courses.lesson')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StepSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Ожидает проверки'), ('graded', 'Оценено')], default='submitted', max_length=20)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('grading_source', models.CharField(choices=[('manual', 'Преподаватель'), ('llm', 'ИИ')], default='manual', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='content.step')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
