# Generated by Django 6.0.5 on 2026-05-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='step_type',
            field=models.CharField(choices=[('text', 'Текст'), ('video', 'Видео'), ('quiz', 'Тест'), ('test_case', 'Тест-кейс'), ('sort', 'Сортировка'), ('match', 'Сопоставление'), ('free_answer', 'Свободный ответ')], max_length=20),
        ),
    ]
